### ISSUE TITLE
Changing MongoDB architecture

### ISSUE THREAD

**Issue by abrobbins90** [abrobbins90/groceries#18]
Right now, the Mongo database has the following collections: [admin, nodes, users]
Specifically, the nodes collection has one document for each node, including for different users. This seems like poor organization

I propose that the database has one collection for each user. This way, each user's data would be fully separated, but also all together in one place. Instead of a nodes and users collection, all information for a single user can be in their own collection. (Though password information can still be fully separated in the admin node).

For example, there may be a collection called "u_freebsd"
This can have a document like is already in the current "users" collection which contains basic info as well as a list of nodes. Then the remaining documents can be the user's nodes, such as what is already in the "nodes" collection.

**Comment by MareoRaft** [comment]
I think that one of the main reasons for using collections is to group/separate data with the same/different structure.  For example, [here](https://docs.mongodb.com/manual/core/databases-and-collections/#document-validation) there is a feature where you may enforce some sort of data model on all documents within a single collection.

Having a separate collection for each user would work, but I don't see any particular advantage.  Maybe there is an advantage that has not occurred to me.

Thoughts:

  * If we decide to use the document validation feature, we would need to deploy the validation on each collection. (minor)
  * Queries are run against single collections.  If we ever released a feature or needed a functionality in the future that wanted to search for recipes across users, we would need to run a query for each user. (future proofing)
  * A mongo collection is analogous to an SQL table.  You can find a lot of stuff online about having "one table per user".  So far I have only read [this page](https://stackoverflow.com/questions/7544544/database-efficiency-table-per-user-vs-table-of-users).

**Comment by abrobbins90** [comment]
Hmm, I read the SQL reference. If that is true for Mongo as well, then I guess this is ok. Though I am playing around with alternatives as well. Thoughts:
- Can Mongo search a level lower from a document? Should we have a document for each users' nodes? Or just have a field in each document for the user and user that to ensure searching is fast?
- Should we have a different collection for each type of node? This arguably could be beneficial for large searches as their data structures will vary. And if we ever need to search all nodes for something, that will still only be a handful of collections to search. Although I guess if you can just have a document field for this, it's a non-issue? I need to learn more about querying...

**Comment by MareoRaft** [comment]
## Can Mongo search a level lower from a document?

If by a "level lower" you mean a nested document, then I'm pretty sure yes.

    {
        "key": "value",
        "key2": {
            "i am": "nested"
        }
    }

The inner document is called a "nested document" in the [mongo docs](https://docs.mongodb.com/manual/tutorial/query-embedded-documents/), which are really well written IMHO and a good resource in general.

## Should we have a document for each users' nodes?

Well we already have a document for each user, and that document contains an array of the node id's of the nodes that they own.

We also already have a document for each node.

## Or just have a field in each document for the user and use that to ensure searching is fast?

Doesn't seem necessary right now, since we are maintaining an array of node id's for the nodes that the user owns.  So currently we are fetching the user's nodes by id, which is fast.

## Should we have a different collection for each type of node?

It could go either way.  Like if meal nodes and ingredient nodes are sufficiently different, then they should be separate.  But currently they seem similar enough.  Searches can filter on the node's "type" key.

## I need to learn more about querying

Read [this page](https://docs.mongodb.com/manual/tutorial/query-documents/) to start.  Also, here is a [Mongo CRUD pdf file](https://github.com/MareoRaft/notes/blob/master/mongo%20CRUD%20cheatsheet.pdf) that shows some cool tricks.

**Comment by MareoRaft** [comment]
hope i was helpful :)

**Comment by abrobbins90** [comment]
Definitely a helpful reference for queries. Yes it's coming back to me.
Though it seems if we have a dictionary within a document, we won't be able to easily search anything about that or at least I didn't see anything about that.
Ok, well I guess what we have now is fine. I'll probably always feel slightly off about all user data being stored together, but certainly right now, it's not a problem.
